import { ConfigProvider } from 'antd';
import StyledComponentsRegistry from '@/lib/antdRegistry';
import 'antd/dist/reset.css';
import './global.scss';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <ConfigProvider prefixCls="mix">
          <StyledComponentsRegistry>{children}</StyledComponentsRegistry>
        </ConfigProvider>
      </body>
    </html>
  );
}
