
@HOST={{$dotenv NEXTAUTH_URL}}

### 创建用户
POST {{HOST}}/api/user
content-type: application/json

{
  "usename": "sobird",
  "email": "sobird@126.com"
}

### 为用户添加角色
POST {{HOST}}/api/user/1/role
content-type: application/json

{
  "ids": [3]
}

### 创建角色
POST {{HOST}}/api/role
content-type: application/json

{
  "name": "管理员-创建",
  "description": "这是普通管理员角色-创建"
}

### 更新角色
PATCH {{HOST}}/api/role/1
content-type: application/json

{
  "name": "管理员-更新",
  "description": "这是普通管理员角色-更新"
}

### 删除角色
DELETE {{HOST}}/api/role/2
content-type: application/json

### Comment GET
# @name comments
GET http://{{HOST}}/api/comments
?pn=1
&ps=20


### Comment POST

@LastId = {{comments.response.body.$.data.rows[0].id}}
POST http://{{HOST}}/api/comments
content-type: application/json

{
  "id": {{LastId}},
  "author": "sobird",
  "content": "评论内容1 {{$guid}}",
  "email": "sobird@126.com"
}