
# user model curd

@HOST={{$dotenv NEXTAUTH_URL}}

### 用户登录
POST {{HOST}}/api/auth/login
content-type: application/json

{
  "username": "sobird",
  "password": "sobird"
}

### 创建用户
@usernameToPost=sobird-{{$randomInt 1 1000}}
POST {{HOST}}/api/user
content-type: application/json

{
  "username": "{{usernameToPost}}",
  "email": "{{usernameToPost}}@test.com"
}

### 查询所有用户
# @name getUsers
GET {{HOST}}/api/user
content-type: application/json

### 查询单个用户
# @name getUser
# @prompt id 手动输入ID
GET {{HOST}}/api/user/{{id}}
content-type: application/json

### 更新查询出来的用户
@userIdToPatch = {{getUser.response.body.$.id}}
@usernameToPatch = {{getUser.response.body.$.username}}-patched
PATCH {{HOST}}/api/user/{{userIdToPatch}}
content-type: application/json

{
  "usename": "{{usernameToPatch}}",
  "email": "{{usernameToPatch}}@test.com"
}

### 删除用户
@userIdToDelete = {{getUser.response.body.$.id}}
DELETE {{HOST}}/api/user/{{userIdToDelete}}

### 查询用户下的所有角色
@userIdToGetRole = {{getUser.response.body.$.id}}
GET {{HOST}}/api/user/{{userIdToGetRole}}/role

### 为查询出来的角色添加用户
@userIdToAddRole = {{getUser.response.body.$.id}}
# @prompt roleId 手动输入roleId
POST {{HOST}}/api/user/{{userIdToAddRole}}/role
content-type: application/json

{
  "ids": [{{roleId}}]
}

### 强制同步role模型表
PUT {{HOST}}/api/user/